// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package ost

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Task_StateType int32

const (
	Task_Initial    Task_StateType = 0
	Task_InProgress Task_StateType = 1
	Task_Done       Task_StateType = 2
	Task_Deleted    Task_StateType = 3
)

var Task_StateType_name = map[int32]string{
	0: "Initial",
	1: "InProgress",
	2: "Done",
	3: "Deleted",
}
var Task_StateType_value = map[string]int32{
	"Initial":    0,
	"InProgress": 1,
	"Done":       2,
	"Deleted":    3,
}

func (x Task_StateType) String() string {
	return proto.EnumName(Task_StateType_name, int32(x))
}
func (Task_StateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_task_35f332b8c4769075, []int{0, 0}
}

type Task struct {
	Id                   uint64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Deleted              bool          `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	States               []*Task_State `protobuf:"bytes,5,rep,name=states,proto3" json:"states,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_35f332b8c4769075, []int{0}
}
func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (dst *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(dst, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *Task) GetStates() []*Task_State {
	if m != nil {
		return m.States
	}
	return nil
}

type Task_State struct {
	Type                 Task_StateType       `protobuf:"varint,1,opt,name=type,proto3,enum=ost.Task_StateType" json:"type,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Task_State) Reset()         { *m = Task_State{} }
func (m *Task_State) String() string { return proto.CompactTextString(m) }
func (*Task_State) ProtoMessage()    {}
func (*Task_State) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_35f332b8c4769075, []int{0, 0}
}
func (m *Task_State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task_State.Unmarshal(m, b)
}
func (m *Task_State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task_State.Marshal(b, m, deterministic)
}
func (dst *Task_State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task_State.Merge(dst, src)
}
func (m *Task_State) XXX_Size() int {
	return xxx_messageInfo_Task_State.Size(m)
}
func (m *Task_State) XXX_DiscardUnknown() {
	xxx_messageInfo_Task_State.DiscardUnknown(m)
}

var xxx_messageInfo_Task_State proto.InternalMessageInfo

func (m *Task_State) GetType() Task_StateType {
	if m != nil {
		return m.Type
	}
	return Task_Initial
}

func (m *Task_State) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type Project struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tasks                []*Task  `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_35f332b8c4769075, []int{1}
}
func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (dst *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(dst, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func init() {
	proto.RegisterType((*Task)(nil), "ost.Task")
	proto.RegisterType((*Task_State)(nil), "ost.Task.State")
	proto.RegisterType((*Project)(nil), "ost.Project")
	proto.RegisterEnum("ost.Task_StateType", Task_StateType_name, Task_StateType_value)
}

func init() { proto.RegisterFile("task.proto", fileDescriptor_task_35f332b8c4769075) }

var fileDescriptor_task_35f332b8c4769075 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0xb1, 0xe3, 0x7e, 0xe4, 0x2a, 0x95, 0xc8, 0x2c, 0x56, 0x97, 0x46, 0x5d, 0x9a, 0xc9,
	0x95, 0xca, 0xc2, 0xc6, 0xd2, 0xa5, 0x0b, 0xaa, 0x4c, 0xff, 0x80, 0x4b, 0x8e, 0x2a, 0xfd, 0x88,
	0xa3, 0xf8, 0x18, 0xfa, 0x57, 0xf8, 0xb5, 0x28, 0x0e, 0x09, 0x08, 0x89, 0xcd, 0x7e, 0xfd, 0xe8,
	0x7c, 0xef, 0x03, 0x40, 0xd6, 0x9f, 0x75, 0x55, 0x3b, 0x72, 0x32, 0x72, 0x9e, 0x66, 0xf3, 0xa3,
	0x73, 0xc7, 0x0b, 0xae, 0x42, 0x74, 0xf8, 0x78, 0x5f, 0x51, 0x71, 0x45, 0x4f, 0xf6, 0x5a, 0xb5,
	0xd4, 0xe2, 0x93, 0x83, 0xd8, 0x5b, 0x7f, 0x96, 0x53, 0xe0, 0x45, 0xae, 0x58, 0xca, 0x32, 0x61,
	0x78, 0x91, 0x4b, 0x09, 0xa2, 0xb4, 0x57, 0x54, 0x51, 0xca, 0xb2, 0xd8, 0x84, 0xb3, 0x54, 0x30,
	0xca, 0xf1, 0x82, 0x84, 0xb9, 0x12, 0x29, 0xcb, 0xc6, 0xa6, 0xbb, 0xca, 0x25, 0x0c, 0x3d, 0x59,
	0x42, 0xaf, 0x06, 0x69, 0x94, 0x4d, 0xd6, 0xf7, 0xda, 0x79, 0xd2, 0xcd, 0x60, 0xfd, 0xda, 0xe4,
	0xe6, 0xfb, 0x79, 0x76, 0x82, 0x41, 0x08, 0xe4, 0x12, 0x04, 0xdd, 0x2a, 0x0c, 0x3f, 0x4e, 0xd7,
	0x0f, 0x7f, 0xf8, 0xfd, 0xad, 0x42, 0x13, 0x00, 0xf9, 0x04, 0x71, 0xbf, 0xb4, 0xe2, 0x29, 0xcb,
	0x26, 0xeb, 0x99, 0x6e, 0x6b, 0xe9, 0xae, 0x96, 0xde, 0x77, 0x84, 0xf9, 0x81, 0x17, 0xcf, 0x10,
	0xf7, 0xc3, 0xe4, 0x04, 0x46, 0xdb, 0xb2, 0xa0, 0xc2, 0x5e, 0x92, 0x3b, 0x39, 0x05, 0xd8, 0x96,
	0xbb, 0xda, 0x1d, 0x6b, 0xf4, 0x3e, 0x61, 0x72, 0x0c, 0x62, 0xe3, 0x4a, 0x4c, 0x78, 0x83, 0x6d,
	0xda, 0x4e, 0x49, 0xb4, 0x78, 0x81, 0xd1, 0xae, 0x76, 0x27, 0x7c, 0xa3, 0x7f, 0xf5, 0xf0, 0x5f,
	0x7a, 0xe6, 0x30, 0x68, 0xfc, 0x7b, 0x15, 0x05, 0x07, 0x71, 0xdf, 0xc9, 0xb4, 0xf9, 0x61, 0x18,
	0xf6, 0x7d, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x94, 0xc5, 0x1c, 0xa7, 0x01, 0x00, 0x00,
}
